### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by shannonmoeller** [choojs/nanomorph#105]
Open issues and PRs with no updates to master in 9 months. Wondering if I should switch back to morphdom.

**Comment by olstenlarck** [comment]
No it's not. See, i believe, the `beta` branch.

Also much comments are happening on the issues. As i know there are some blockers.

Aside of that, it still is doing its thing great, no matter how many months are gone.

**Comment by shannonmoeller** [comment]
> No it's not.

Great to hear.

> it still is doing its thing great

Yes it is! Except for [the thing I need](https://github.com/choojs/nanomorph/pull/97). :)

**Comment by olstenlarck** [comment]
Haha.. daaaamn, how time flies.

Don't know what's happening, actually, but probably is because @yoshuawuyts gone to Rust in recent months.

**Comment by soyuka** [comment]
@shannonmoeller can't you use own branch instead of the npm published package? I do this on a lot of projects, open source rhythm will mostly not follow your own imo.

**Comment by shannonmoeller** [comment]
That's exactly what I'm doing, but that's incompatible with unpkg.com for example.

https://unpkg.com/nanomorph@github:shannonmoeller/nanomorph#cc1b2b6?module

**Comment by shannonmoeller** [comment]
I gave up and just embedded the beta branch into my project for now. Looking forward to new releases!

https://www.npmjs.com/package/apply-html
