### ISSUE TITLE
Better usage example?

### ISSUE THREAD

**Issue by mgibbs189** [choojs/nanomorph#66]
Hello, I'm trying to use nanomorph on the entire `<body>`. I'm getting an HTML string via ajax (see `inject`). The goal is to update the DOM body by updating only the changed nodes (instead of destroying/replacing everything). What am I missing here?

```js
var inject = "string of HTML, e.g. $('body').html()";
var tree = morph(inject, $('body').html());
console.log(tree); // undefined
```

Thanks in advance

**Comment by soyuka** [comment]
It doesn't work with strings but rather real elements. This is why we use [bel](https://github.com/shama/bel) or hyperscript libraries. For this to work you need to use DOM Element instances instead of strings. Note that both arguments of the `morph` function should be Elements.

**Comment by yoshuawuyts** [comment]
I think the question's been answered. Closing for now! Let us know if you have any other questions! :D
