### ISSUE TITLE
[question] the list of events

### ISSUE THREAD

**Issue by tgfjt** [choojs/nanomorph#82]
Hi!

Sometimes I think "Oh, `onanimationend`, `fullscreenchange` are missing in event.js" but "Then what is missing? how can we make it all listed?"

Yes I can make a PR to add tho, Do you have a policy to add Events into [event.js] ?(https://github.com/choojs/nanomorph/blob/master/lib/events.js)

Thanks.

**Comment by yoshuawuyts** [comment]
@tgfjt hey, sorry for my late reply —but I'd be down with the idea of adding listeners for all non-deprecated events! Thanks :grin:

**Comment by tgfjt** [comment]
@yoshuawuyts It's good to hear.:)

**Comment by yoshuawuyts** [comment]
@tgfjt still interested in adding more events? C:

**Comment by tgfjt** [comment]
@yoshuawuyts 
yeah, but I'm actually interested in "how" to get the name of events.:)
looking at MDN or something like that??
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers

I think that adding events is easy matter but I'm not in trouble now.:P

**Comment by yoshuawuyts** [comment]
Haha, yeah that would be the list I think. If there's nothing missing at the moment, should we close this issue? Or should we perhaps add an entry to FAQ on the repo?

**Comment by tgfjt** [comment]
@yoshuawuyts 
Thanks! Time to close.:)
Let's see what happens!
