### ISSUE TITLE
can't set 'onchange' event in select tag

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/nanomorph#84]
I just ran into this but I'm not sure if it is my mistake or an issue.
When setting something like 

```js
function mainView (state, emit) {
  return html`
    <body>
      <select onchange="${onchange}">
        ${state.opts.map((opt, i) => {
          return html`<option value="${i}">${opt}</option>`
        })}
      </select>
      <button onclick=${onclick}>Run</button>
    </body>
  `

  function onclick () {
    console.log('click!')
  }
  function onchange() {
    console.log('change!')
  }
}
```

The click event is normally attached to the button, but the change event isn't attached to the select tag.
I saw in [comments](https://github.com/choojs/nanomorph/blob/master/lib/morph.js#L26-L27) that some elements need _speacial_ treatment to set events, but there is no special treatment for select tags, even tho [there is in morphdom](https://github.com/patrick-steele-idem/morphdom/blob/master/src/specialElHandlers.js#L60). Is there something missing? or am I doing something wrong?

**Comment by yoshuawuyts** [comment]
Could you perhaps write a test case for this? We have like 400 tests at the moment; and legit the only way to make this stuff work, and prevent regressions is through testing. Thanks!

Even though we seem to be looking out for `onchange` in our events though (https://github.com/choojs/nanomorph/blob/master/lib/events.js#L32) — I think you might be right we're missing something.

**Comment by YerkoPalma** [comment]
This snippet can reproduce the issue for me.

```js
var morph = require('nanomorph')
var html = require('bel')

var tree = html`
<div>
  <select onchange="${onchange}">
    <option>1</option>
    <option>2</option>
  </select>
</div>`
document.body.appendChild(tree)

morph(tree, html`
<div>
  <p>morphed!</p>
  <select onchange="${onchange}">
    <option>A</option>
    <option>B</option>
  </select>
</div>`)

function onchange (e) {
  e.preventDefault()
  alert('change')
}
```

![image](https://user-images.githubusercontent.com/5105812/31408834-35a0c2a4-ade0-11e7-905d-df594ff1c506.png)

As you can see, the content is correctly morphed, but there is no change event bound to the select tag

**Comment by him2him2** [comment]
@yoshuawuyts
I added some event testing for this issue. The tests pass. The event testing code I added should be useful for almost all event testing. Please take a look and let me know if you have any feedback.

@YerkoPalma
I don't think that the onchange (e)  is correct. Probably erroring out on e.preventDefault(). The onchange signature is onchange ()...I think.

#88

**Comment by yoshuawuyts** [comment]
@him2him2 thanks so much for the tests! — having more of these tests would be amazing to have; they're the only line of defense we have against introducing regressions; so the more, the better! :grin:

**Comment by YerkoPalma** [comment]
@him2him2 thanks for testing.

> Is this error possibly the result of the quotes

Oh yeah :sob: I've faced this error before, can't test now but I'm almost sure this is the cause. Totally my fault, sorry.
Closing.
