### ISSUE TITLE
questions before switching from morphdom

### ISSUE THREAD

**Issue by sido420** [choojs/nanomorph#94]
I'm planing to switch from morhdom due to the size of this library. I have read the FAQs already. 

I wanted to know, if there is a way to find out if nanomorph supports a browser or not?

Does nanomorph gracefully degrade on unsupported browsers?

**Comment by yoshuawuyts** [comment]
heya! - nanomorph works on pretty much all browsers. We're not doing anything fancy; so go ahead and give it a shot! :grin:
