### ISSUE TITLE
usage without  require/module manager

### ISSUE THREAD

**Issue by sido420** [choojs/nanomorph#95]
I haven't modified my project to use any kind of module manager yet. So, is this possible to use nanomorph by using regular script tags only?

what would be required if this cant be done through npm? 

I use *-umd files from morpdom.

**Comment by goto-bus-stop** [comment]
You can use the https://wzrd.in browserify cdn to get a UMD module bundle that you can use in a script tag:

```html
<script src="https://wzrd.in/standalone/nanomorph"></script>
<script src="https://wzrd.in/standalone/bel"></script>
<script>
nanomorph(document.body, bel`
  <body>
    <h1>it works!</h1>
  </body>
`)
</script>
```

https://jsfiddle.net/z5w7t3ow/

**Comment by sido420** [comment]
Thanks.

**Comment by AlbanMinassian** [comment]
try <https://bundle.run/nanomorph@5.4.2> alse
